const asset = (name) => `/assets/${name}`;

export const sProject = {
  name: 'S Project',
  slug: 's-project',
  layout: {
    bodySize: '0.9rem',
    sectionMax: '74rem',
    sectionSpace: 'clamp(4rem, 8vw, 7rem)',
    statementMax: '66rem',
    statementLead: '1.08fr',
    statementDetail: '0.92fr',
  },
  hero: {
    image: asset('s-project-hero-warm-v2.jpg'),
    imageAlt: 'S Project contemporary residence concept with architectural linework',
    eyebrow: 'Residential building',
    title: 'S Project',
    text: 'Homes designed for the way life is lived.',
    headlineVariant: 's-project',
    align: 'center',
    eyebrowPosition: 'after',
    height: 'calc(100svh - 4rem)',
    imagePosition: 'center',
    layout: 'full-bleed',
    scrollOnWheel: true,
    heroTreatment: 'soft-highlight',
    imageBrightness: 0.98,
    imageContrast: 1.08,
    imageSaturation: 1.04,
    imageWarmth: 0,
    imageHue: '0deg',
    imageBrightnessGradient: 'vertical',
    imageBrightnessTop: 0.72,
    imageBrightnessBottom: 0.91,
    contentTranslateY: '-10%',
    wordmark: { variant: 's-project', construction: 'image', image: asset('s-project-logo-914.png') },
  },
  statement: {
    lead: 'S Project creates considered residential homes across Melbourne, bringing together design, construction and enduring liveability.',
    detail: 'Every home is a collaboration. We listen closely, design with intention and build with care — creating spaces that feel beautifully resolved and made to last.',
    variant: 'split',
  },
  sections: [
    {
      id: 's-project-collections',
      type: 'collections',
      eyebrow: 'Residential work',
      title: 'A considered way to build.',
      minCardWidth: '15rem',
      referenceColumns: 3,
      referenceCount: 3,
      items: [
        { title: 'Custom Homes', text: 'Bespoke homes designed around your lifestyle, site and vision.', src: asset('update914/s-project-custom-homes.webp'), alt: 'Double-height living room opening onto a garden', ratio: 'portrait' },
        { title: 'Design & Build', text: 'A seamless end-to-end service that brings clarity and craft to every stage.', src: asset('update914/s-project-design-build.webp'), alt: 'Architectural plans and material samples on a design studio table', ratio: 'portrait' },
        { title: 'Melbourne Projects', text: 'Thoughtfully crafted homes across Melbourne’s most sought-after neighbourhoods.', src: asset('update914/s-project-melbourne-projects.webp'), alt: 'Contemporary Melbourne residence framed by eucalyptus trees', ratio: 'portrait' },
      ],
    },
    {
      id: 's-project-feature',
      type: 'feature',
      eyebrow: 'Selected residential work',
      title: 'Homes shaped around the way life is lived.',
      text: 'Our residential work brings together architecture, interiors, materials and landscape to create considered homes with a clear sense of place. From the overall flow of each space to the textures and details within it, every element is carefully selected to create homes that feel cohesive, personal and made to last.',
      image: asset('s-project-residential-work.jpg'),
      alt: 'Considered S Project residence with a warm, layered interior',
      ratio: 'portrait',
      variant: 'media-left-text-right',
      layout: { maxWidth: '74rem' },
    },
  ],
  cta: {
    href: 'https://sproject.com.au/',
    note: 'Independent website — launching 2026',
    sectionId: 's-project-collections',
  },
};
