const asset = (name) => `/assets/${name}`;

export const flux = {
  name: 'FLUX',
  slug: 'flux',
  layout: {
    bodySize: '0.82rem',
    sectionMax: '74rem',
    sectionSpace: 'clamp(4rem, 7vw, 6.5rem)',
    statementMax: '60rem',
    statementLead: '1.08fr',
    statementDetail: '0.92fr',
  },
  hero: {
    image: asset('flux-hero-main.png'),
    imageAlt: 'Brushed metal FLUX wall tapware above a sculptural stone basin',
    title: 'FLUX',
    text: 'Flow Within Minimal Forms.',
    headlineVariant: 'flux',
    height: 'calc(100svh - 4rem)',
    imagePosition: 'center',
    layout: 'full-bleed',
    scrollOnWheel: true,
    imageBrightness: 0.6,
    imageContrast: 0.95,
    imageSaturation: 1.05,
    imageWarmth: 0.06,
    wordmark: { variant: 'flux', construction: 'flux-constructed', image: asset('flux-logo-white-tight.png') },
  },
  statement: {
    lead: 'Born in Melbourne, FLUX creates refined architectural tapware for contemporary Australian kitchens and bathrooms. Inspired by the movement of water, every piece balances restrained form, considered proportion and lasting performance. Engineered for Australia’s coastal conditions, FLUX brings enduring design and dependable function to residential and commercial spaces nationwide.',
    image: asset('flux-statement-main.png'),
    imageAlt: 'FLUX wall-mounted tapware in a green tiled bathroom',
    variant: 'split',
  },
  sections: [
    {
      id: 'flux-collections',
      type: 'collections',
      eyebrow: 'Collections',
      title: 'Designed for everyday rituals.',
      minCardWidth: '15rem',
      referenceColumns: 2,
      referenceCount: 2,
      items: [
        { title: 'Bath & Shower', text: 'Complete bath and shower solutions that balance form, function and flow.', src: asset('flux-bath-shower-main.png'), alt: 'Brushed metal FLUX bath and shower fittings in a white tiled bathroom', ratio: 'portrait' },
        { title: 'Kitchen', text: 'Performance-driven tapware for kitchens where beauty meets everyday use.', src: asset('flux-kitchen-update821.png'), alt: 'Warm white FLUX kitchen cabinetry with a refined mixer', ratio: 'portrait' },
      ],
    },
    {
      id: 'flux-feature',
      type: 'feature',
      eyebrow: 'Sculptural restraint',
      title: 'Made for the rituals of everyday life.',
      text: 'From the first touch of the handle to the final flow of water, FLUX tapware brings calm precision and considered design to daily rituals. Each piece is shaped with restrained form, balanced proportions and enduring performance, creating a quiet sense of clarity in contemporary kitchens and bathrooms.',
      mediaLayout: 'flux-triptych',
      mediaReferenceCount: 3,
      mediaItems: [
        { area: 'bath', image: asset('flux3-1.png'), alt: 'FLUX finish samples arranged on a stone surface', ratio: 'landscape' },
        { area: 'kitchen', image: asset('flux3-2.png'), alt: 'Polished FLUX kitchen mixer and matching dispenser', ratio: 'landscape' },
        { area: 'detail', image: asset('flux3-3.png'), alt: 'FLUX tapware collection displayed on sculptural plinths', ratio: 'landscape' },
      ],
      variant: 'text-left-media-right',
      layout: { maxWidth: '68rem', textColumn: '0.55fr', mediaColumn: '1.45fr' },
    },
  ],
  cta: { href: 'https://flux.com.au/', note: 'Independent website — launching 2026', sectionId: 'flux-collections' },
};
