const asset = (name) => `/assets/${name}`;

export const flux = {
  name: 'FLUX',
  slug: 'flux',
  layout: {
    bodySize: '0.82rem',
    sectionMax: '74rem',
    sectionSpace: 'clamp(4rem, 7vw, 6.5rem)',
    statementMax: '60rem',
    statementLead: '1.08fr',
    statementDetail: '0.92fr',
  },
  hero: {
    image: asset('flux-hero.webp'),
    imageAlt: 'Matte black FLUX tapware over a stone basin',
    eyebrow: 'Tapware',
    title: 'FLUX',
    text: 'Form in motion.',
    headlineVariant: 'flux',
    eyebrowPosition: 'after',
    height: 'clamp(28rem, 49vw, 39rem)',
    imagePosition: 'center',
    layout: 'product-split',
    wordmark: { variant: 'flux', construction: 'flux-constructed' },
  },
  statement: {
    lead: 'FLUX creates refined tapware for contemporary Australian bathrooms and kitchens — considered in proportion, finish and everyday performance.',
    image: asset('flux-ritual.webp'),
    imageAlt: 'FLUX tapware beside a sculptural stone basin',
    variant: 'split',
  },
  sections: [
    {
      id: 'flux-collections',
      type: 'collections',
      eyebrow: 'Collections',
      title: 'Designed for everyday rituals.',
      minCardWidth: '15rem',
      referenceColumns: 2,
      referenceCount: 3,
      items: [
        { title: 'Basin', text: 'Sculptural tapware for basins and vanity spaces.', src: asset('flux-basin.webp'), alt: 'FLUX basin tapware in a stone vanity', ratio: 'portrait' },
        { title: 'Bath & Shower', text: 'Complete bath and shower solutions that balance form, function and flow.', src: asset('flux-bath-shower.webp'), alt: 'FLUX shower fitting against warm plaster', ratio: 'portrait' },
        { title: 'Kitchen', text: 'Performance-driven tapware for kitchens where beauty meets everyday use.', src: asset('flux-kitchen.webp'), alt: 'FLUX kitchen mixer tap', ratio: 'portrait' },
      ],
    },
    {
      id: 'flux-finishes',
      type: 'swatches',
      eyebrow: 'Finishes, considered',
      title: 'A finish for every space.',
      referenceColumns: 4,
      referenceCount: 4,
      items: [
        { name: 'Brushed Nickel', color: 'linear-gradient(135deg, #bcb7ad, #79766f)' },
        { name: 'Brushed Brass', color: 'linear-gradient(135deg, #c8a36a, #78511e)' },
        { name: 'Gunmetal', color: 'linear-gradient(135deg, #5d5d58, #242523)' },
        { name: 'Matte Black', color: '#20211f' },
      ],
    },
    {
      id: 'flux-feature',
      type: 'feature',
      eyebrow: 'Sculptural restraint',
      title: 'Made for living beautifully.',
      text: 'From the first touch to the last, FLUX tapware brings a sense of calm and clarity to daily rituals.',
      mediaLayout: 'flux-triptych',
      mediaReferenceCount: 3,
      mediaItems: [
        { area: 'primary', image: asset('flux-ritual.webp'), alt: 'FLUX basin tapware with stone vessel', ratio: 'square' },
        { area: 'detail', image: asset('flux-ritual-detail.webp'), alt: 'Close detail of a FLUX tap control', ratio: 'wide' },
        { area: 'room', image: asset('flux-ritual-room.webp'), alt: 'FLUX bath tapware in a calm bathroom', ratio: 'wide' },
      ],
      variant: 'text-left-media-right',
      layout: { maxWidth: '68rem', textColumn: '0.55fr', mediaColumn: '1.45fr' },
    },
  ],
  cta: { href: 'https://flux.com.au/', note: 'Independent website — launching 2026' },
};
