const asset = (name) => `/assets/${name}`;

export const interich = {
  name: 'INTERICH',
  slug: 'interich',
  layout: {
    bodySize: '0.84rem',
    sectionMax: '76rem',
    sectionSpace: 'clamp(4rem, 7vw, 6.5rem)',
    statementMax: '54rem',
    statementLead: '1fr',
    statementDetail: '1fr',
  },
  hero: {
    image: asset('interich-hero-wide.webp'),
    imageAlt: 'Refined INTERICH kitchen with natural timber cabinetry',
    eyebrow: 'Custom cabinetry',
    title: 'INTERICH',
    align: 'center',
    eyebrowPosition: 'after',
    height: 'clamp(29rem, 52vw, 42rem)',
    imagePosition: 'center',
    layout: 'full-bleed',
    overlay: true,
    wordmark: { variant: 'interich', construction: 'interich-type' },
  },
  statement: {
    title: 'Designed. Manufactured. Installed.',
    lead: 'INTERICH creates considered cabinetry for kitchens, wardrobes and complete interiors — designed, manufactured and installed in Melbourne.',
    detail: 'Crafted for modern living, every detail is resolved around how a home feels and functions.',
    variant: 'centered',
  },
  sections: [
    {
      id: 'interich-feature',
      type: 'feature',
      eyebrow: 'Designed for living',
      title: 'Crafted for modern living.',
      text: 'From concept to completion, our in-house team delivers cabinetry with uncompromising quality at every stage.',
      image: asset('interich-hero.webp'),
      alt: 'Timber and stone kitchen by INTERICH',
      ratio: 'landscape',
      variant: 'text-left-media-right',
      layout: { maxWidth: '66rem', textColumn: '0.6fr', mediaColumn: '1.4fr' },
    },
    {
      id: 'interich-collections',
      type: 'collections',
      eyebrow: 'Cabinetry collections',
      title: 'All under one roof.',
      minCardWidth: '15rem',
      referenceColumns: 3,
      referenceCount: 3,
      items: [
        { title: 'Kitchens', text: 'Functional. Beautiful. Enduring.', src: asset('interich-kitchens.webp'), alt: 'INTERICH kitchen cabinetry', ratio: 'square' },
        { title: 'Wardrobes', text: 'Tailored storage for everyday living.', src: asset('interich-wardrobes.webp'), alt: 'Timber wardrobe and dressing room', ratio: 'square' },
        { title: 'Whole-home Cabinetry', text: 'Seamless spaces from room to room.', src: asset('interich-whole-home.webp'), alt: 'Integrated living-room cabinetry', ratio: 'square' },
      ],
    },
    {
      id: 'interich-manufacturing',
      type: 'feature',
      eyebrow: 'Made in Melbourne',
      title: 'Local manufacturing. Lasting precision.',
      text: 'Our state-of-the-art facility brings design and manufacture together, allowing quality to be considered in every component.',
      image: asset('interich-manufacturing.webp'),
      alt: 'Craftsperson working in the INTERICH manufacturing facility',
      ratio: 'wide',
      variant: 'text-left-media-right',
      layout: { maxWidth: '76rem', textColumn: '0.68fr', mediaColumn: '1.32fr' },
    },
  ],
  cta: { href: 'https://interich.com.au/', note: 'Independent website — launching 2026' },
};
