const asset = (name) => `/assets/${name}`;

export const interich = {
  name: 'INTERICH',
  slug: 'interich',
  layout: {
    bodySize: '1rem',
    copySize: 'clamp(1rem, 1.35vw, 1.2rem)',
    copyMax: '40rem',
    sectionMax: '76rem',
    sectionSpace: 'clamp(4rem, 7vw, 6.5rem)',
    statementMax: '54rem',
    statementLead: '1fr',
    statementDetail: '1fr',
  },
  hero: {
    image: asset('update922/interich-hero.webp'),
    imageAlt: 'INTERICH living room framed by illuminated display cabinetry',
    eyebrow: 'Custom cabinetry',
    title: 'INTERICH',
    align: 'center',
    eyebrowPosition: 'after',
    height: 'calc(100svh - 4rem)',
    imagePosition: 'center',
    layout: 'full-bleed',
    overlay: true,
    imageBrightness: 0.6,
    imageContrast: 0.98,
    imageWarmth: 0.08,
    imageHue: '-6deg',
    imageSaturation: 1.13,
    imageBrightnessGradient: 'vertical',
    scrollOnWheel: true,
    contentMax: '64rem',
    wordmark: { variant: 'interich', construction: 'interich-type', image: asset('interich-logo-white.png') },
  },
  statement: null,
  sections: [
    {
      id: 'interich-feature',
      type: 'feature',
      eyebrow: 'Designed for living',
      title: 'Crafted for modern life.',
      text: 'From the first concept to final installation, our in-house team creates cabinetry that brings together considered design, precise detailing and lasting quality. Every element is made to work beautifully within the home, balancing practical function with a refined and enduring sense of style.',
      image: asset('update914/interich-feature.webp'),
      alt: 'Cream cabinetry with an illuminated timber coffee niche',
      ratio: 'landscape',
      variant: 'text-left-media-right',
      layout: { maxWidth: '66rem', textColumn: '0.6fr', mediaColumn: '1.4fr' },
      surface: 'paper',
    },
    {
      id: 'interich-collections',
      type: 'collections',
      eyebrow: 'Cabinetry collections',
      title: 'All under one roof.',
      minCardWidth: '15rem',
      referenceColumns: 3,
      referenceCount: 3,
      mediaScale: '90%',
      mediaGap: 'clamp(1.25rem, 2.5vw, 2.5rem)',
      surface: 'deep',
      items: [
        { title: 'Kitchens', text: 'Functional. Beautiful. Enduring.', src: asset('interich-kitchens-edited.png'), alt: 'INTERICH kitchen cabinetry', ratio: 'square' },
        { title: 'Wardrobes', text: 'Tailored storage for everyday living.', src: asset('interich-wardrobes-edited.png'), alt: 'Timber wardrobe and dressing room', ratio: 'square' },
        { title: 'Whole-home Cabinetry', text: 'Seamless spaces from room to room.', src: asset('interich-whole-home-edited.png'), alt: 'Integrated living-room cabinetry', ratio: 'square' },
      ],
    },
    {
      id: 'interich-manufacturing',
      type: 'feature',
      eyebrow: 'Made in Melbourne',
      title: 'Made locally. Built to last.',
      text: 'Our Melbourne manufacturing facility brings design and production together under one roof. This allows us to maintain close control over every material, detail and finish, while responding carefully to the needs of each project. From the workshop to the home, every piece is made with precision, consistency and care.',
      image: asset('update914/interich-manufacturing.webp'),
      alt: 'Dark display cabinetry with integrated lighting in a refined entry hall',
      ratio: 'wide',
      variant: 'text-left-media-right',
      layout: { maxWidth: '76rem', textColumn: '0.68fr', mediaColumn: '1.32fr' },
      surface: 'paper',
    },
  ],
  cta: {
    href: 'https://interich.com.au/',
    note: 'Independent website — launching 2026',
    sectionId: 'interich-collections',
  },
};
