const asset = (name) => `/assets/${name}`;

export const ioak = {
  name: 'IOAK',
  slug: 'ioak',
  layout: {
    bodySize: '0.82rem',
    sectionMax: '73rem',
    sectionSpace: 'clamp(4rem, 7.5vw, 6.75rem)',
    statementMax: '56rem',
    statementLead: '1.1fr',
    statementDetail: '0.9fr',
  },
  hero: {
    image: asset('ioak-hero.webp'),
    imageAlt: 'Natural oak flooring in a calm modern living room',
    eyebrow: 'Timber flooring',
    title: 'IOAK',
    text: 'Natural foundations for modern living.',
    headlineVariant: 'ioak',
    scrollOnWheel: true,
    eyebrowPosition: 'after',
    height: 'clamp(29rem, 50vw, 40rem)',
    imagePosition: 'center',
    layout: 'full-bleed',
    wordmark: { variant: 'ioak', construction: 'ioak-geometric' },
  },
  statement: {
    lead: 'IOAK brings together considered timber species, refined finishes and precise craftsmanship for enduring Australian interiors.',
    detail: 'We source premium timbers and engineer each board for stability, beauty and performance from the first step to the final detail.',
    variant: 'split',
  },
  sections: [
    {
      id: 'ioak-collections',
      type: 'collections',
      eyebrow: 'Discover the range',
      title: 'Timber with character.',
      minCardWidth: '15rem',
      referenceColumns: 3,
      referenceCount: 3,
      items: [
        { title: 'Natural Oak', text: 'Premium oak timbers with honest texture and timeless appeal.', src: asset('ioak-natural-oak.webp'), alt: 'Natural oak flooring beside a curved stone plinth', ratio: 'square' },
        { title: 'Engineered Timber', text: 'Engineered for stability and longevity, suited to contemporary Australian living.', src: asset('ioak-engineered-timber.webp'), alt: 'Engineered timber stairs and flooring', ratio: 'square' },
        { title: 'Signature Finishes', text: 'Curated finishes that enhance the natural beauty of real timber.', src: asset('ioak-signature-finishes.webp'), alt: 'Herringbone timber flooring detail', ratio: 'square' },
      ],
    },
    {
      id: 'ioak-materials',
      type: 'feature',
      eyebrow: 'Material, grain, character',
      title: 'The beauty is in the detail.',
      text: 'Timber is a natural material. Its colour, grain and tone vary gently from board to board — creating depth and warmth only real wood can deliver.',
      mediaLayout: 'ioak-pair',
      mediaReferenceCount: 2,
      mediaItems: [
        { area: 'sample', image: asset('ioak-material-samples.webp'), alt: 'Loose oak samples showing grain and finish', ratio: 'square' },
        { area: 'floor', image: asset('ioak-material-detail.webp'), alt: 'Oak flooring boards showing natural grain', ratio: 'landscape' },
      ],
      variant: 'text-left-media-right',
      layout: { maxWidth: '68rem', textColumn: '0.62fr', mediaColumn: '1.38fr' },
    },
    {
      id: 'ioak-factory',
      type: 'feature',
      eyebrow: 'Made in Melbourne',
      title: 'Local capability. Lasting performance.',
      text: 'IOAK timber flooring is designed and finished in Melbourne, with dedicated facilities and service supporting every project.',
      image: asset('ioak-factory.webp'),
      alt: 'IOAK manufacturing facility exterior',
      ratio: 'banner',
      variant: 'text-left-media-right',
      layout: { maxWidth: '73rem', textColumn: '0.65fr', mediaColumn: '1.35fr' },
    },
  ],
  cta: {
    href: 'https://ioak.com.au/',
    note: 'Independent website — launching 2026',
    sectionId: 'ioak-factory',
  },
};
