const asset = (name) => `/assets/${name}`;

export const ioak = {
  name: 'IOAK',
  slug: 'ioak',
  layout: {
    bodySize: '0.82rem',
    sectionMax: '73rem',
    sectionSpace: 'clamp(4rem, 7.5vw, 6.75rem)',
    statementMax: '56rem',
    statementLead: '1.1fr',
    statementDetail: '0.9fr',
  },
  hero: {
    image: asset('ioak-hero-main.png'),
    imageAlt: 'Bright minimalist living room with oak flooring and floor-to-ceiling windows',
    eyebrow: 'Timber flooring',
    title: 'IOAK',
    text: 'Natural foundations for modern living.',
    headlineVariant: 'ioak',
    scrollOnWheel: true,
    eyebrowPosition: 'after',
    height: 'calc(100svh - 4rem)',
    imagePosition: 'center',
    layout: 'full-bleed',
    imageBrightness: 1,
    imageBrightnessGradient: 'right-to-left',
    imageContrast: 0.95,
    imageSaturation: 1.05,
    imageWarmth: 0.06,
    wordmark: {
      variant: 'ioak',
      construction: 'ioak-geometric',
      image: asset('ioak-logo-white-tight.png'),
    },
  },
  statement: {
    image: asset('ioak-introduction.png'),
    imageAlt: 'IOAK timber flooring and material details',
    lead: 'IOAK specialises in premium multi-layer engineered timber flooring, created for interiors where natural material, refined design and lasting performance matter.',
    detail: 'Each collection is developed to preserve the warmth, grain and individuality of real timber, while offering the stability required for modern homes. Thoughtful tones, refined finishes and enduring quality define the IOAK approach to flooring.',
    variant: 'split',
  },
  sections: [
    {
      id: 'ioak-collections',
      type: 'collections',
      eyebrow: 'Discover the range',
      title: 'Timber with character.',
      minCardWidth: '15rem',
      referenceColumns: 3,
      referenceCount: 3,
      items: [
        { title: 'Natural Oak', text: 'Premium oak timbers with honest texture and timeless appeal.', src: asset('update914/ioak-natural-oak.webp'), alt: 'Natural oak herringbone flooring in soft sunlight', ratio: 'square' },
        { title: 'Engineered Timber', text: 'Engineered for stability and longevity, suited to contemporary Australian living.', src: asset('update914/ioak-engineered-timber.webp'), alt: 'Wide engineered timber floorboards beside an open book', ratio: 'square' },
        { title: 'Signature Finishes', text: 'Curated finishes that enhance the natural beauty of real timber.', src: asset('update914/ioak-signature-finishes.webp'), alt: 'Textured oak finish samples in natural light', ratio: 'square' },
      ],
    },
    {
      id: 'ioak-materials',
      type: 'feature',
      eyebrow: 'Material, grain, character',
      title: 'The beauty is in the detail.',
      text: 'Timber is a natural material. Its colour, grain and tone vary gently from board to board — creating depth and warmth only real wood can deliver.',
      mediaLayout: 'ioak-pair',
      mediaReferenceCount: 2,
      mediaItems: [
        { area: 'sample', image: asset('update914/ioak-detail-1.webp'), alt: 'Pale oak samples showing subtle grain and finish', ratio: 'square' },
        { area: 'floor', image: asset('update914/ioak-detail-2.webp'), alt: 'Fanned timber samples showing contrasting natural tones', ratio: 'landscape' },
      ],
      variant: 'text-left-media-right',
      layout: { maxWidth: '68rem', textColumn: '0.62fr', mediaColumn: '1.38fr' },
    },
    {
      id: 'ioak-factory',
      type: 'feature',
      eyebrow: 'Made in Melbourne',
      title: 'Local capability. Lasting performance.',
      text: 'IOAK timber flooring is designed and finished in Melbourne, with dedicated facilities and service supporting every project.',
      image: asset('ioak-factory-edited.png'),
      alt: 'IOAK manufacturing facility exterior',
      ratio: 'banner',
      variant: 'text-left-media-right',
      layout: { maxWidth: '73rem', textColumn: '0.65fr', mediaColumn: '1.35fr' },
    },
  ],
  cta: {
    href: 'https://ioak.com.au/',
    note: 'Independent website — launching 2026',
    sectionId: 'ioak-collections',
  },
};
